# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PYTHON\exchange\pyhton_exchance_1\ui\room_detail.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.groupBox.setObjectName("groupBox")
        self.txtnum = QtWidgets.QLineEdit(self.groupBox)
        self.txtnum.setGeometry(QtCore.QRect(150, 40, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtnum.setFont(font)
        self.txtnum.setObjectName("txtnum")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtfoor = QtWidgets.QLineEdit(self.groupBox)
        self.txtfoor.setGeometry(QtCore.QRect(150, 100, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtfoor.setFont(font)
        self.txtfoor.setObjectName("txtfoor")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox)
        self.btnAdd.setGeometry(QtCore.QRect(10, 200, 41, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnDel = QtWidgets.QPushButton(self.groupBox)
        self.btnDel.setGeometry(QtCore.QRect(80, 200, 41, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnEdit = QtWidgets.QPushButton(self.groupBox)
        self.btnEdit.setGeometry(QtCore.QRect(150, 200, 41, 31))
        self.btnEdit.setObjectName("btnEdit")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(210, 200, 41, 31))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(270, 200, 41, 31))
        self.btnCancel.setObjectName("btnCancel")
        self.btnExit = QtWidgets.QPushButton(self.groupBox)
        self.btnExit.setGeometry(QtCore.QRect(330, 200, 41, 31))
        self.btnExit.setObjectName("btnExit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 280, 391, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ข้อมูลห้องพัก"))
        self.groupBox.setTitle(_translate("MainWindow", "ข้อมูลห้องพัก"))
        self.label.setText(_translate("MainWindow", "เลขห้อง"))
        self.label_2.setText(_translate("MainWindow", "ชั้น"))
        self.label_3.setText(_translate("MainWindow", "ประเภทห้อง"))
        self.btnAdd.setText(_translate("MainWindow", "เพิ่ม"))
        self.btnDel.setText(_translate("MainWindow", "ลบ"))
        self.btnEdit.setText(_translate("MainWindow", "เเก้ไข"))
        self.btnSave.setText(_translate("MainWindow", "บันทึก"))
        self.btnCancel.setText(_translate("MainWindow", "ยกเลิก"))
        self.btnExit.setText(_translate("MainWindow", "ออก"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "เลขห้อง"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ชั้น"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ประเภทห้องพัก"))

